name = "WebAPI"
uuid = "5556bdb8-3a7d-4ae1-af17-2e5edce21069"
authors = ["Elias Carvalho <eliascarvdev@gmail.com> and contributors"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
HTTP = "0.9"
JSON3 = "1"
julia = "1.6"
